# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 708566a1715257b56325120f65ec3b7a0c122ba4be0e7b449a66badc72f531974f5fc0275ce28dae69bafe8ffd620712b2cc0fd315035f0c9ad532fa422311a8

test:
  secret_key_base: dc688a8bced52853b38cabedaf8b88ab8646c598a16361b4f8ca2ca83d90f8a915b3f6fdabc6e0ba97960ff017e13b04b742acceba5b8c14a9f3c2d5dbf04657

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
